### PR TITLE
Configurable URIs

### PR DESCRIPTION
**Pull request by alancleary**
Addresses issue #42. The Compose File approach needs testing.

FYI: We may need to revisit this when we tackle issue #18 but I think it's fine for now since we're trying to get this into production.

### CODE REVIEW

**Comment by adf-ncgr** [comment]
I'm probably doing something wrong but when I try to run using:
docker compose -f compose.yml -f compose.dev.yml up --build --force-recreate
I get an error:
graphql-server-graphql-server-1  | Error: GWASResult.ontologyAnnotations defined in resolvers, but not in schema
although ./src/types/GWASResult.graphql does seem to define it:
```
type GWASResult implements Annotatable {
  # Annotatable
  id: ID!
  identifier: ID!
  ontologyAnnotations: [OntologyAnnotation!]!
```
will beat my head against it but if anyone already knows what the issue is let me know.

**Comment by adf-ncgr** [comment]
Ah, I think the issue is that the compose-dev file was just using
`command: serve:dev`
changing to 
`command: start`
seems to have gotten things to fully build. Can commit the change if that is indeed the right approach?

**Comment by alancleary** [comment]
> Ah, I think the issue is that the compose-dev file was just using `command: serve:dev` changing to `command: start` seems to have gotten things to fully build. Can commit the change if that is indeed the right approach?

Hmm, it sounds like Docker was trying to use a cached image since building the code is part of the image build process, i.e. `npm run serve:dev` should've worked. I think changing the dev command to `start` still makes sense, though, because in the dev use case we want the code to be rebuilt every time there's a change. Good catch!

**Comment by svengato** [comment]
That also solves the "Connection reset by peer" problem I had on wolfburn.

**Comment by svengato** [comment]
On the `configurable-uris` branch, with

`INTERMINE_URI=https://mines.legumeinfo.org/arachismine/service`

(with or without quotes) in `.env`, this curl command (which works fine for the `main` branch)

```
curl --request POST --header 'content-type: application/json' --url http://localhost:4444/ --data '{ "query": "query { organisms { results { commonName, genus, species }}}" }'
```

gives this error:

```
{"errors":[{"message":"Invalid URL","locations":[{"line":1,"column":9}],"path":["organisms"],"extensions":{"code":"INTERNAL_SERVER_ERROR","stacktrace":["TypeError [ERR_INVALID_URL]: Invalid URL","    at new NodeError (node:internal/errors:399:5)","    at new URL (node:internal/url:577:13)","    at IntermineAPI.resolveURL (/app/node_modules/@apollo/datasource-rest/dist/RESTDataSource.js:41:16)","    at IntermineAPI.fetch (/app/node_modules/@apollo/datasource-rest/dist/RESTDataSource.js:167:32)","    at IntermineAPI.get (/app/node_modules/@apollo/datasource-rest/dist/RESTDataSource.js:113:28)","    at IntermineAPI.pathQuery (file:///app/dist/data-sources/intermine/intermine.server.js:40:27)","    at IntermineAPI.searchOrganisms (file:///app/dist/data-sources/intermine/api/search-organisms.js:25:30)","    at Object.organisms (file:///app/dist/resolvers/intermine/organism.js:22:44)","    at field.resolve (file:///app/node_modules/@apollo/server/dist/esm/utils/schemaInstrumentation.js:36:28)","    at executeField (/app/node_modules/graphql/execution/execute.js:481:20)"]}}],"data":{"organisms":null}}
```

**Comment by alancleary** [comment]
@svengato Can you clarify that this is using Docker? @adf-ncgr seems to have identified this issue with the Docker already.

**Comment by svengato** [comment]
Yes, it is using `compose.dev.yml` with "start" instead of "serve:dev".

Removing the INTERMINE_URI line from `.env` has no effect, it looks for MiniMine instead of ArachisMine but gives the same error.

**Comment by svengato** [comment]
Also confirmed the same problem for other curl commands, like one with 'traits' instead of 'organisms'.

**Comment by alancleary** [comment]
> Yes, it is using `compose.dev.yml` with "start" instead of "serve:dev".
> 
> Removing the INTERMINE_URI line from `.env` has no effect, it looks for MiniMine instead of ArachisMine but gives the same error.

OK, thanks. It's an issue with how I coded the environment variables in the `compose.yml` file. I just guessed on the syntax :upside_down_face: @adf-ncgr is working on straightening it out.

**Comment by adf-ncgr** [comment]
@alancleary I don't think it's a syntax issue I think the issue is that the method you're using in the code is not finding the .env file in the container context but wiping out the environment settings that were getting injected via the compose file. Doing something like this (which I found on the internet):
```
// load environment variables from the .env file into process.env
const result = config();
// Only override process.env if .env file is present and valid
if (!result.error) {
  Object.keys(result.parsed).forEach((key) => {
    const value = result.parsed[key];
    if (value) {
      process.env[key] = value;
    }
  });
}
```
seems to allow the docker stuff to preserve these being injected through the compose file while presumably also working when not in containerland. This seems a bit clumsy, an alternative might be to use volumes to make the .env file available inside the container, but I haven't figured that out yet. If you think the above approach is fine, I'll just go with that.

**Comment by alancleary** [comment]
@adf-ncgr The `.env` file is [specifically excluded](https://github.com/legumeinfo/graphql-server/blob/main/.dockerignore#L5) from the container to ensure the environment inside the container is consistent no matter where it was built. [`process.env`](https://nodejs.org/api/process.html#processenv) should see the environment variables inside the container's environment, including those set in `compose[.*].yml`. So I'm pretty sure this is a compose related syntax error... I'll look into it.

**Comment by sammyjava** [comment]
Doesn't having the .env file in the repo defeat the purpose of being able to change the URIs without changing a repo file? Normally I don't store .env files in repositories.

**Comment by adf-ncgr** [comment]
@alancleary you're right I was confused by my diagnostics. The syntax issue seems to be that you don't want to put double quotes around the variables in the compose.yml file ie:
     environment:
```
-      - INTERMINE_URI="${INTERMINE_URI}"
-      - MICROSERVICES_URI="${MICROSERVICES_URI}"
+      - INTERMINE_URI=${INTERMINE_URI}
+      - MICROSERVICES_URI=${MICROSERVICES_URI}
```
seems to make it work as intended

**Comment by adf-ncgr** [comment]
> Normally I don't store .env files in repositories.

I don't think we were proposing to do that either.

**Comment by svengato** [comment]
Yes, it works now. What about the quotes in the "${PORT:-4000}:4000" line just above?

**Comment by alancleary** [comment]
@adf-ncgr Good catch! I guess that makes sense since the value of the variable should already have quotes so adding quotes in the compose file gives it double quotes. Aye!

@sammyjava Agreed, the `.env` file shouldn't be in the repo, and it's not anymore thanks to you! I added it to the `.dockerignore` file so someone won't accidentally build a container with their local `.env` file and get inconsistent behavior as compared to the image on GHCR, for example.

**Comment by alancleary** [comment]
> Yes, it works now. What about the quotes in the "${PORT:-4000}:4000" line just above?

[That syntax is fine](https://docs.docker.com/compose/networking/).

**Review by adf-ncgr — APPROVED** [review]
I think we're good to go now.

**Review by sammyjava — APPROVED** [review]
Works for me!

**Review by svengato — APPROVED** [review]
Fine with me -

**Pull request merged**
