### PR TITLE
Updated Dockerfile to use Node LTS base image.

### PR DESCRIPTION
**Pull request by alancleary**

### CODE REVIEW

**Comment by alancleary** [comment]
@adf-ncgr Mind testing this sometime today? I want to be sure it's not a "works on my computer" scenario before adding it to the imminent release.

**Comment by adf-ncgr** [comment]
sure, I will give it a try and let you know

**Review by adf-ncgr — COMMENTED** [review]
Sorry this took a little longer than it should have. Was having some weird sporadic connectivity issues when testing on a VM but it works fine on my laptop and on a deployment to a different VM, so I think it must be something janky about my network setup on the first VM I borrowed for testing purposes. It's hard to imagine how the error I was seeing could be related to the change in base imagine, in any case.

**Review by adf-ncgr — APPROVED** [review]
thought I approved with my last comment, apparently not

**Pull request merged**
