### PR TITLE
Added Newick type and Phylotree.newick attribute

### PR DESCRIPTION
**Pull request by sammyjava**
Feel free to kill this. Because Newick is an InterMine class, and I didn't want to deviate from how we query InterMine, I created a Newick type so that I can then resolve a Phylotree.newick field, providing the Phylotree.newick.content string. This is because Phylotree does not have a Newick reference, so I cannot query Newick directly from Phylotree.

That is something I could change in a future mine version, where we could query Phylotree.newick.content.

The reason Newick is a separate class in InterMine has to do with large strings and indexing. Newick is a "simple" class without an id, which means it doesn't get indexed or included in the object store. And I don't want it to be. (Another example of a simple class is ExpressionValue.)

Not all the mines have populated Phylotree/Newick (same loader). But the current dev MiniMine 5.1.0.3 does have the Phylotree/Newick classes populated:

INTERMINE_URI=https://mines.dev.lis.ncgr.org/minimine/service

Also, the production GlycineMine 5.1.0.2 has them as well. I'd been moving away from storing Phylotree since I link off to another site from the gene family, but now that we're looking at querying Phylotree in graphql I'll populate it in all the mines.

### CODE REVIEW

**Comment by sammyjava** [comment]
Of course, if you just want the Newick and you've got a gene family identifier, you can just get the Newick with that identifier.

**Comment by alancleary** [comment]
I think it make sense for the Newick tree (i.e. the `Newick` type's `content` field) to just be a string field of the `Phylotree` type in the GraphQL API because the Newick is just a different representation of the same tree data. Of course this wouldn't change the Intermine model so we would have to translate between the GraphQL API and the Intermine model via the resolvers.

Also, is line 27 in `src/resolvers/intermine/phylotree.ts` correct, i.e. is the Newick identifier the same as the Phylotree identifier?

**Comment by sammyjava** [comment]
> Also, is line 27 in `src/resolvers/intermine/phylotree.ts` correct, i.e. is the Newick identifier the same as the Phylotree identifier?

Yeah, that's kind of the whole idea, which is why there is no Phylotree.newick. I can't query the newick via Phylotree so I have to query it via a get-newick routine. And the get-foo routines want a model. And a model wants a graphql type. So the whole thing cascaded up to me having to create a Newick type to be consistent with our design.

I can add Phylotree.newick in 5.1.0.4 and we can just hold off on this. But 5.1.0.3 is well underway so we're talking probably a half year or so before that happens. Unless I bail on my current builds and add Phylotree.newick to 5.1.0.3 and start over with the builds. I think a GraphQL temporary solution like this makes a lot more sense. Phylotree.newick.content isn't the end of the world for a temporary solution.

**Comment by sammyjava** [comment]
But we can populate a string field Phylotree.newick from the Newick object, I guess. I just figured that I'd go with the normal routine, if we've got a Type, we use that Type and then pull it's fields down the chain. So, Phylotree.newick.content rather than Phylotree.newick for the time being. But no strong opinion on that. And if you want to wrangle stuff to draw content from the Newick mine object (using Phylotree.identifier) without having a Newick type, feel free! I just didn't want to veer into a different way of querying and resolving.

**Comment by sammyjava** [comment]
Again I keep forgetting that I have a standalone Newick object in the mines for performance reasons. I don't want to index that huge "meaningless" content in keyword search or the object store. I did that first and it really slowed things down. So, now that I remember that, we need to stick with a standalone Newick object in the mines and deal with populating Phylotree on the graphql side.

**Comment by alancleary** [comment]
> Again I keep forgetting that I have a standalone Newick object in the mines for performance reasons. I don't want to index that huge "meaningless" content in keyword search or the object store. I did that first and it really slowed things down. So, now that I remember that, we need to stick with a standalone Newick object in the mines and deal with populating Phylotree on the graphql side.

This is totally fine. The beauty of the GraphQL approach is that we don't need data model parity between Intermine and GraphQL. I think the parity-by-default approach that we've been taking is good, but this seems like an instance where deviating makes sense.

**Comment by alancleary** [comment]
@sammyjava I added a commit to this PR that removes the Newick GraphQL type and makes the `newick` field of the `Phylotree` type the newick string. Check it out.

**Comment by sammyjava** [comment]
Ahhh, so we have `graphqlNewickAttributes` to be able to run the query and load stuff into a JSON for Phylotree.newick resolution, but we don't have the Newick type to store that stuff. That's sort of the ultimate extension of the "temporary" fields like organismIdentifier that we use, where everything is a "temporary" field.

I am getting null for the Newick, though.

**Comment by alancleary** [comment]
> Ahhh, so we have `graphqlNewickAttributes` to be able to run the query and load stuff into a JSON for Phylotree.newick resolution, but we don't have the Newick type to store that stuff. That's sort of the ultimate extension of the "temporary" fields like organismIdentifier that we use, where everything is a "temporary" field.

Yeah, you were 90% of the way there.

> I am getting null for the Newick, though, which is where I was when I tried this yesterday. :)

Did you use `INTERMINE_URI=https://mines.dev.lis.ncgr.org/minimine/service`? The default mine doesn't seem to have any newick.

**Review by alancleary — APPROVED** [review]

**Pull request merged**
