### PR TITLE
Add gene search parameters

### PR DESCRIPTION
**Pull request by alancleary**
Code looked good while I was resolving merge conflicts when adding in main. Needs testing.

### CODE REVIEW

**Comment by sammyjava** [comment]
Back to throwing errors: I think you only want one copy of the error in the returned array rather than two. I didn't catch this earlier.
image
```json
{
  "data": {
    "gene": null
  },
  "errors": [
    {
      "message": "Gene with primaryIdentifier 'cicar.ICC4958.gnm2.ann1.Ca_' not found",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "gene"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT",
        "stacktrace": [
          "GraphQLError: Gene with primaryIdentifier 'cicar.ICC4958.gnm2.ann1.Ca_' not found",
          "    at inputError (file:///home/shokin/graphql-server/dist/utils/input-error.js:4:11)",
          "    at Object.gene (file:///home/shokin/graphql-server/dist/resolvers/intermine/gene.js:8:17)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
        ]
      }
    },
    {
      "message": "Gene with primaryIdentifier 'cicar.ICC4958.gnm2.ann1.Ca_' not found",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "gene"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT",
        "stacktrace": [
          "GraphQLError: Gene with primaryIdentifier 'cicar.ICC4958.gnm2.ann1.Ca_' not found",
          "    at inputError (file:///home/shokin/graphql-server/dist/utils/input-error.js:4:11)",
          "    at Object.gene (file:///home/shokin/graphql-server/dist/resolvers/intermine/gene.js:8:17)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
        ]
      }
    }
  ]
}
```

**Comment by sammyjava** [comment]
Otherwise my random testing of queries looks good. Gene linkouts still look good, Location linkouts look good.

**Comment by alancleary** [comment]
Interesting. Apparently this issue is present in main as well so I don't think it's a blocker for this PR. Time to do some code archeology...

**Comment by sammyjava** [comment]
Yeah we can mop it up later. I'll approve.

**Comment by alancleary** [comment]
It appears this is an issue with Apollo Explorer. If I make the same request via curl then the result only contains the error once:

```bash
curl --request POST \
    --header 'content-type: application/json' \
    --url http://localhost:4000/ \
    --data '{"query":"query Query($identifier: ID!) {\n  gene(identifier: $identifier) {\n    identifier\n    name\n  }\n}","variables":{"identifier":"cicar.ICC4958.gnm2.ann1.Ca_"}}'
```
```json
{
  "errors":[
    {
      "message":"Gene with primaryIdentifier 'cicar.ICC4958.gnm2.ann1.Ca_' not found",
      "locations":[
        {
          "line":2,
          "column":3
        }
      ],
      "path":[
        "gene"
      ],
      "extensions":{
        "code":"BAD_USER_INPUT",
        "stacktrace":[
          "GraphQLError: Gene with primaryIdentifier 'cicar.ICC4958.gnm2.ann1.Ca_' not found",
          "    at inputError (file:///home/alan/Projects/ncgr/lis-legfed/legumeinfo/graphql/graphql-server/dist/utils/input-error.js:4:11)",
          "    at Object.gene (file:///home/alan/Projects/ncgr/lis-legfed/legumeinfo/graphql/graphql-server/dist/resolvers/intermine/gene.js:8:17)",
          "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"
        ]
      }
    }
  ],
  "data":{
    "gene":null
  }
}
```
Using the network monitor in my web  browser, I see that Apollo Explorer makes this same request. If I load the request in its own window, the result only contains 1 error. So something in Apollo Explorer is causing it to show the error twice, i.e. there's nothing wrong on the server side!

**Comment by sammyjava** [comment]
Weird! Very weird! I suppose we should report it to Apollo but then we'd have to make a simple test case to show it which sounds like actual work. :) Nice work sussing that out!

**Pull request merged**
