### PR TITLE
modifications for using bun instead of node

### PR DESCRIPTION
**Pull request by adf-ncgr**
not sure if the compose.prod.yml will need to be changed (well, it obviously will in terms of a new release image, but in addition to that). I am not sure I completely knew what I was doing when tweaking the way the serve commands are invoked but dimly recall some apparent need to do so (ie not just s/npm/bun/g)

### CODE REVIEW

**Comment by adf-ncgr** [comment]
should add that @ctcncgr did some stress testing on the instance I had set up and it seemed to pass with flying colors according to his report.

**Comment by alancleary** [comment]
@adf-ncgr Let's hold off on merging this until @ctcncgr to the following comment/question I raised on Slack (it sounds like he's working on it now):

> The GraphQL server caches query responses by default so unless the benchmark is intended to use the cache the server should either be run with the cache disabled or each query (and its subqueries, ad infinitum) should be unique

I'll add that we want to avoid cache hits in this case because it seems like the code that's breaking is related to non-cached code paths in the GraphQL server.

**Comment by adf-ncgr** [comment]
@alancleary fine to hold off but I'll note that when I first observed the issue that led us to try this as a solution, I was just reloading the page to send the same query every time and seeing it basically fail every other time. So, not sure how that squares with the caching behavior you describe? Seems like after it succeeded once then subsequent page loads should have also succeeded, but maybe I'm misunderstanding you.

**Comment by alancleary** [comment]
> @alancleary fine to hold off but I'll note that when I first observed the issue that led us to try this as a solution, I was just reloading the page to send the same query every time and seeing it basically fail every other time. So, not sure how that squares with the caching behavior you describe? Seems like after it succeeded once then subsequent page loads should have also succeeded, but maybe I'm misunderstanding you.

Interesting. In that case I'm not sure if the cache is related to the issue or not. @ctcncgr seems to have verified that the cache isn't an issue with Bun. I guess we might as well see what happens when the cache is disabled since this is much more likely to overwhelm the server, i.e. have the server working on many requests simultaneously.

**Comment by adf-ncgr** [comment]
@alancleary I think I fixed #164 with the recent commit but please have a look at the comment and see if you care that the start command no longer invokes serve:dev; for reasons completely obscure to me, build:watch does not seem to be functioning in the bun environment, so I subverted it that way.

**Comment by alancleary** [comment]
@adf-ncgr I'm not sure we should commit to replacing npm with bun in the `package.json` scripts since this would require developers that want to use their local environment to install bun. An alternative approach could be to alias `npm` and `node` in the `Dockerfile` to use bun. What do you think?

Also, I played around with it and I think I have all of the commands working now. I can commit the necessary changes once we decide on whether to update `package.json` or use aliases in the `Dockerfile`.

**Comment by adf-ncgr** [comment]
@alancleary you are more opinionated than I ever will be about such things but I trust your judgment. If you can make it work the way you've described (and it sounds like you already have) I am happy to follow what you've cooked up.

**Comment by alancleary** [comment]
OK it looks like the alias solution will actually be a bit kludgy so I'm just going to rip the band-aid and switch the whole GraphQL repo to Bun. But that will happen tomorrow.

**Comment by adf-ncgr** [comment]
works for me, thanks!

**Comment by alancleary** [comment]
@adf-ncgr I just  pushed commits that should (hopefully) finish the transition to bun. Mind testing it out?

**Comment by adf-ncgr** [comment]
will do

**Comment by adf-ncgr** [comment]
works for me- note that my testing was in the context of using docker compose dev mode, hopefully that's what you had in mind. One question, did you intend to add the file bun.lockb to the repo?

**Comment by alancleary** [comment]
> did you intend to add the file bun.lockb to the repo?

Yes. It's bun's equivalent of `package-lock.json`, which has been removed since the repo now uses bun. Speaking of which, I should update `README.md` to talk about bun instead of npm.

**Pull request merged**
