### PR TITLE
added github action for publishing image to container registry on tag

### PR DESCRIPTION
**Pull request by adf-ncgr**
I think this is the needful, basically copied from microservices, then simplified (I'm assuming that we have only a single target image in this case). Untested, not sure if there is a good way to test other than pushing a tag...

### CODE REVIEW

**Comment by adf-ncgr** [comment]
I should note that we also probably need a way to inject the mine URL that we're targeting through some configuration mechanism- which I think is what #42 is all about. Maybe that should be considered a blocker for this?

**Comment by sammyjava** [comment]
(Only because I feel like if we don't treat it as a blocker here we may never deal with it. And we do tend to use MiniMine for development, so we're swapping that URL in a file.)

**Review by alancleary — CHANGES_REQUESTED** [review]
I think release tags shouldn't have the prefix "graphql-server@". This scheme is used in the microservices repo to differentiate what service a release tag is for. It's not necessary here because this is not a monorepo.

Since the `compose.prod.yml` file is being updated to use an image, the `build: .` line should be moved from the `compose.yml` file into the `compose.dev.yml` file.

Regarding loading mine and microservice URIs at run-time, I agree this is a good idea. The `index.ts` file is already using [dotenv](https://www.dotenv.org/) to support loading environment variables from both the environment and a `.env` file (see [line 11](https://github.com/legumeinfo/graphql-server/blob/c0353147335ffdf2e473e5ac6115246e6992ea06/src/index.ts#L11)) so the environment variables designated for these URIs can be set via the Docker Compose YAML files; no need to hard-code them in the GHCR images. After all we want other sites in our group to be able to use the GHCR images too!

As for actually implementing loading these values from the environment, I think it's bad form to load environment variables in files other than the main `index.ts` file that starts the server. Fortunately the data sources are instantiated [using a factory function](https://github.com/legumeinfo/graphql-server/blob/c0353147335ffdf2e473e5ac6115246e6992ea06/src/data-sources/index.ts#L17) so adding the URIs as parameters to the factory instead of as hard-coded values is an easy solution (the [context factory function](https://github.com/legumeinfo/graphql-server/blob/c0353147335ffdf2e473e5ac6115246e6992ea06/src/context.ts#L11) will need to be updated as well). I can implement these changes to the factory if you would like.

**Comment by sammyjava** [comment]
> . I can implement these changes to the factory if you would like.

Definitely. I don't even understand what you wrote. :)

**Comment by alancleary** [comment]
Sorry for the delay on this. Has this been tested? If not, you can test it by forking the repo, merging this branch, and tagging a release.

**Comment by sammyjava** [comment]
I presume you're asking @adf-ncgr to test it. Let me know if you want me to.

**Comment by sammyjava** [comment]
We also had the task of getting the mine and microservices URIs out of the repo code. Maybe that's a different PR.

**Comment by alancleary** [comment]
I don't think it matters who tests it. And, yes, moving the URIs to environment variables should be a different PR. I suggest waiting until issue #43 is resolved. It's going to be a helluva merge!

**Comment by adf-ncgr** [comment]
It hasn't been tested- forking is a good idea, I'll do that.

**Comment by adf-ncgr** [comment]
tested, seemed to work once I got the permissions on my organization set to allow writing to the container registry; result is here: https://github.com/adf-ncgr/graphql-server/pkgs/container/graphql-server

let me know if anything else needed

**Review by alancleary — CHANGES_REQUESTED** [review]
OK, I tested the image you published to GHCR and it's working as expected.

One final request: can you update the `Dockerfile` so that `serve:prod` is the default command? I think having the container itself run the server in production mode is more prudent than overriding the command in the docker compose file.

**Review by alancleary — APPROVED** [review]
Thanks!

**Comment by alancleary** [comment]
@adf-ncgr Is there any reason this hasn't been merged?

**Comment by adf-ncgr** [comment]
no, I don't think so, I just forgot it was a thing

**Pull request merged**
